import {Metadata} from "next";
import "./globals.css";
import Header from "./components/header";

export const metadata: Metadata = {
  title: {
    template: "%s | NY Bestsellers",
    default: "Loading...",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-5xl mx-auto">
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
